mainname: Go Quality Check

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22.0'
    
    - name: Install dependencies
      run: go mod download
          
    - name: Run static code analysis
      run: |
        go get -u golang.org/x/lint/golint
        golint ./...
      
    - name: Run GitHub Copilot suggestions
      run: |
        # Run GitHub Copilot suggestions for all Go files in the repository
        for file in $(find . -name "*.go"); do
          suggestions=$(copilot --file $file)
          if [ -n "$suggestions" ]; then
            echo "Suggestions for $file:"
            echo "$suggestions"
          fi
        done
